server:
  port: 9004 # 服务访问端口号
spring:
  application:
    name: sxicode-article # 服务名称
  datasource: # 数据库连接4大属性
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://110.41.19.90:3306/tensquare_article?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    mongodb:
      host: 110.41.19.90
      database: commentdb
  redis:
    host: 110.41.19.90
    port: 6379
#Mybatis-Plus配置
mybatis-plus:
  type-aliases-package: com.sxicode.article.pojo
  global-config:
    id-type: 1 #0：数据库ID自增 1：用户输入ID
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置缓存的全局开关
    lazy-loading-enabled: true #延时加载开关
    multiple-result-sets-enabled: true #开启延时加载，否则按需加载
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句，调试用
